### ISSUE TITLE
Sometimes platforms don't spawn (or at least not in range)

### ISSUE THREAD

**Issue by arcutright** [ianlav/EECS393IsaacGameThing#11]
Proof
![capture](https://cloud.githubusercontent.com/assets/22824937/20283889/e6cb7738-aa88-11e6-877d-4418e738043e.PNG)

To replicate: play enough times, it happens to me quite often

**Comment by ianlav** [comment]
The level generation trigger no longer destroys platforms, which is what caused this issue. The monster now destroys platforms when it touches them
