### ISSUE TITLE
Steamrolling enemies can be a legit strategy

### ISSUE THREAD

**Issue by arcutright** [ianlav/EECS393IsaacGameThing#12]
I'm assuming this was already fixed in local commits or is a quick fix of damage-per-time during collisions, but this is silly: [Here's a really low fps gif of the issue](http://g.recordit.co/xp3H58rRbd.gif)

I feel like it should be more punishing than a single damage calculation applied at the initial time of contact.

**Comment by ianlav** [comment]
Fixed. Player takes damage every tenth of a second from enemy contact
