### ISSUE TITLE
Game over screen not working sometimes?

### ISSUE THREAD

**Issue by arcutright** [ianlav/EECS393IsaacGameThing#14]
Monster collision does not always switch to game over screen, but hp=0 does. Not sure why yet.

**Comment by ianlav** [comment]
The monster is currently in its own layer which screws with some collision detection. I had to remove some code placing various objects in separate layers so other code could work. I'm not sure why they were placed in those layers to begin with

**Comment by arcutright** [comment]
Nope, it was my fault. Forgot to add the scene to the build settings. Fixed in 5e390f7532bec70cd49a1a287bdafcfd6021bf26.
